### ISSUE TITLE
[Suggestion] Hour/Minute/Second labels

### ISSUE THREAD

**Issue by RichardGG** [YclepticStudios/pebble-timer-plus#4]
Just to make the app more understandable for newcomers.

A simple H, M and S under each number would make it easier to understand.

Many people still seem to find the old version more intuitive, I think this may be a factor in that.

**Comment by YclepticStudios** [comment]
Thank you for your concerns and feedback. However, I will not be adding these. I feel that the benefits of having a clean design outweigh the initial uncertainty of what each field represents.
