### ISSUE TITLE
Making you aware of a reported deep crash problem by a Google+ user

### ISSUE THREAD

**Issue by MaggieLeber** [YclepticStudios/pebble-timer-plus#5]
I've had no such problem myself but you might want to reach out:

https://plus.google.com/u/0/+NateFlemingPickles123/posts/TSEZpuQoFWE

**Comment by YclepticStudios** [comment]
Thank you! Doesn't look to be a widespread occurrence based on my usage stats... 

Anyway, if it is an issue with running older apps on the new firmware (this shouldn't be an issue), I have a few tweaks which I plan on adding soon, so I will release a recompiled version soon.

**Comment by MaggieLeber** [comment]
Just thought you'd like to know...thanks for stopping by G+.

**Comment by YclepticStudios** [comment]
No problem. Thanks for letting me know about it!
